config/routes.rb
DashBoard::Application.routes.draw do

  devise_for :users

  root :to => "dashboard/items#index"
  
  namespace :dashboard do
    resources :items
  end
  
  get 'tag/:name' => 'tag#show', :as => 'show_tagged_items'
  
  ActionDispatch::Routing::Translator.translate_from_file('config/locales/routes.yml', { :prefix_on_default_locale => true, :keep_untranslated_routes => true })

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :item
  attr_accessible :filename, :order
  validates :filename, :presence => true
  
  mount_uploader :filename, ImageUploader
  
  def main?
    return false if self.item.blank?
    self == self.item.image
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  belongs_to :image
  has_many :images
  has_and_belongs_to_many :tags
  attr_accessible :body, :title
  attr_accessible :images_attributes
  validates :body, :title, :presence => true
  accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if => proc { |attributes| attributes['filename'].blank? }
  
  def set_tags(tags)
    if (tags.is_a? String)
      tags = tags.split(',');
    end
    
    if ((!tags.is_a? Array) || tags.blank? || !tags.select{ |item| item.blank?}.empty? )
      raise ArgumentError, "Argument must be not empty String separated by comma or Array of such strings"
    end
    
    self.tags.clear
    
    tags.each do |tag_name|
      tag = Tag.find_or_create_by_name(tag_name.strip)
      self.tags << tag
    end
  end
  
  def main_image
    self.image || self.images.first
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, :class_name => "User"
  belongs_to :recipient, :class_name => "User"
  belongs_to :item
  attr_accessible :body
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :items
  attr_accessible :name
  
  
  #Just for fun
  def self.cloud_data
    tags_raw = ActiveRecord::Base.connection.execute("SELECT t.name, COUNT(tag_id) FROM items_tags it LEFT JOIN tags t ON it.tag_id = t.id GROUP BY tag_id")
    avg_raw = ActiveRecord::Base.connection.execute("SELECT AVG(count) FROM (SELECT COUNT(tag_id) count FROM items_tags GROUP BY tag_id) t")
    avg = avg_raw[0][0]
    
    data = Hash.new
    tags_raw.each do |raw|
      data[raw[0]] = raw[1]/avg
    end
    
    data
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :set_locale  
  before_filter :set_locale_from_url
  before_filter :redirect_to_default_client_locale
  
  private
  
  def redirect_to_default_client_locale
    unless params[:locale]
      redirect_to url_for(:only_path => true, :locale => I18n.locale.to_s)
    end
  end
  
  def set_locale
    available = %w{en ru}
    I18n.locale = params[:locale] || http_accept_language.preferred_language_from(available)
  end
end

app/controllers/dashboard/items_controller.rb
class Dashboard::ItemsController < ApplicationController
  
  before_filter :authenticate_user!
  
  def index
    @items = current_user.items
  end
  
  def new
    @item = current_user.items.new
  end
  
  def create
    @item = current_user.items.build(params[:item])
    
    if @item.save
      @item.set_tags(params[:tags])
      redirect_to dashboard_items_url
    else
      render :new
    end
  end
  
  def edit
    @item = current_user.items.find(params[:id])
    @main = 'new'
  end
  
  def update
    @item = current_user.items.find(params[:id]);
    
    if @item.update_attributes(params[:item])
      @item.set_tags(params[:tags])
      @main = params[:main]
      render :edit

      redirect_to dashboard_items_url
    else
      render :edit  
    end
  end
  
  def destroy
    @item = current_user.items.find(params[:id])
    @item.destroy
    redirect_to dashboard_items_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tag_controller.rb
class TagController < ApplicationController
  def show
    tag = Tag.find_by_name(params[:name])
    @items = tag.blank? ? Array.new : tag.items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def new_child_fields_template(form_builder, association, options = {})
    options[:object] ||= form_builder.object.class.reflect_on_association(association).klass.new
    options[:partial] ||= association.to_s.singularize
    options[:form_builder_local] ||= :f
  
    content_tag(:div, :id => "#{association}_fields_template", :style => "display: none") do
      form_builder.fields_for(association, options[:object], :child_index => "new_#{association}") do |f|
        render(:partial => options[:partial], :locals => { options[:form_builder_local] => f })
      end
    end
  end
  
  def add_child_link(name, association)
    link_to(name, "javascript:void(0)", :class => "add_child", :"data-association" => association)
  end
  
  def remove_child_link(name, f)
    f.hidden_field(:_destroy) + link_to(name, "javascript:void(0)", :class => "remove_child")
  end
end

app/helpers/dashboard/items_helper.rb
module Dashboard::ItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tag_helper.rb
module TagHelper
  def tag_cloud
    a = Array.new
    Tag.cloud_data.each do |name, weight|
      a << link_to(name, show_tagged_items_url(name), :style => "font-size: #{(100*weight).round}%")      
    end
    a.join(' ').html_safe
  end
end

app/views/application/_auth.html.haml
- if user_signed_in?
  = link_to current_user.email, edit_user_registration_path
  |
  = link_to t(:sign_out), destroy_user_session_path, method: :delete
- else
  = link_to t(:sign_in), new_user_session_path
  |
  = link_to t(:sing_up), new_user_registration_path

app/views/application/_menu.html.haml
#menu
  - if user_signed_in?
    %ul
      %li= link_to t(:new_item), new_dashboard_item_url
      %li= link_to t(:items_list), dashboard_items_url

app/views/application/_translator.html.haml
- ['ru', 'en'].each do |locale|
  = link_to_unless locale == params[:locale], t(locale), {:locale => locale}

app/views/dashboard/items/_form.html.haml
= debug @main
= form_for @item, as: :item, url: @item.new_record? ? dashboard_items_path : dashboard_item_path(@item), :html => {:multipart => true} do |f|
  =f.error_messages

  #title
    = f.label Item.human_attribute_name(:title)
    = f.text_field :title
  
  #body
    = f.label Item.human_attribute_name(:body)
    %br
    = f.text_area :body, :size => '70x25'
    
  #tags
    = label_tag :tags, t(:tags, :scope => [:item_fields])
    = text_field_tag :tags, f.object.tags.map{|tag| tag.name}.join(', ')
    
  = f.fields_for :images do |fi|
    = render :partial => 'image_fields', :locals => { :f => fi }
  %p=add_child_link t(:add_upload_field, :item => t(:of_image)), :images
  =new_child_fields_template f, :images, :partial => 'image_fields'

  .actions
    = f.submit t(:save)

app/views/dashboard/items/_image_fields.html.haml
#image
  = f.radio_button(:main?, f.object.main?, :name => :main)
  = f.label(f.options[:child_index], :set_as_main,)
  = image_tag(f.object.filename_url(:thumb)) if f.object.filename?
  = f.file_field :filename
  -if f.object.new_record?
    = remove_child_link(t(:remove_field), f)
  -else
    = f.check_box :_destroy
    = f.label :_destroy, t(:remove)

app/views/dashboard/items/edit.html.haml
%h2=t(:edit_item, :title => @item.title)

= render 'form'

app/views/dashboard/items/index.html.haml
%h2=t :your_items
- if (@items.empty?)
  %h3=t(:you_dont_have_items)
- else
  - @items.each do |item|
    =render :partial => 'items/item', :locals => {:item => item}
%br/
= link_to t(:new_item), new_dashboard_item_url

app/views/dashboard/items/new.html.haml
%h2=t(:new_item)

= render 'form'

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/items/_item.html.haml
.item
  .item--title-area
    .item--title= item.title
    .item--create-time
      = item.created_at.strftime('%d-%b-%Y %H:%M')
      = link_to t(:remove), dashboard_item_path(item), method: :delete, data: { confirm: 'Уверены?' }, title: "Удалить"
      = link_to t(:edit), edit_dashboard_item_url(item)
  .item--body
    -if !item.main_image.blank?
      %img{:src => item.main_image.filename_url}
    = simple_format(item.body)
  - unless item.images.empty?
    .item--images
      - item.images.each do |image|
        %img{:src => image.filename_url(:thumb)}
  .item--tags
    =k(item).link_to_tags

app/views/layouts/application.html.haml
!!!
%html
  %head
    %titleDashBoard
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #header
      #auth-area
        = render 'auth'
      #translator-area
        = render 'translator'
  
    #content-area
      #left-area
        = render 'menu'
        = render 'tag/tags'
      #content
        = yield

app/views/tag/_tags.html.haml
#tags
  %div Теги
  = tag_cloud

app/views/tag/show.html.haml
%h2=t :your_items
- if (@items.empty?)
  %h3=t(:you_dont_have_items)
- else
  - @items.each do |item|
    =render :partial => 'items/item', :locals => {:item => item}